Pages/About.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace covidwatch.Pages
{
    public class AboutModel : PageModel
    {
        private readonly ILogger<AboutModel> _logger;

        public AboutModel(ILogger<AboutModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

Pages/Create.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using covidwatch.Model;
using covidwatch.services;
using covidwatch.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace covidwatch.Pages
{
    public class CreateModel : PageModel
    {
        private readonly ILogger<CreateModel> _logger;
        /// private JsonUserReaderService Jsonservice;
        public UsersService DBservice;
        public IEnumerable<User> Users; 
        public AssessmentCenterService ACservice;
        public IEnumerable<AssessmentCenter> AssessmentCenters;
        
        public string Username { get; set; }
        public string Password { get; set; }
        private object jsonservice;

        public CreateModel(ILogger<CreateModel> logger, JsonUserReaderService jurs, UsersService uServ, AssessmentCenterService aServ) 
        {
            _logger = logger;
            jsonservice = jurs;
            DBservice = uServ;
            ACservice = aServ;
        }
        public void OnGet()
        {
            Users = DBservice.Get();
            AssessmentCenters = ACservice.Get();
        }
        public void OnPostSubmit(User newuser)
        {
            this.Username = newuser.Username;
            this.Password = newuser.Password;
            DBservice.Create(newuser);
    
        }
    }
}

Pages/Error.cshtml.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace covidwatch.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

Pages/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace covidwatch.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;

        public IndexModel(ILogger<IndexModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {

        }
    }
}

Pages/Login.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace covidwatch.Pages
{
    public class LoginModel : PageModel
    {
        private readonly ILogger<LoginModel> _logger;

        public LoginModel(ILogger<LoginModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

Pages/Prevention.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace covidwatch.Pages
{
    public class PreventionModel : PageModel
    {
        private readonly ILogger<PreventionModel> _logger;

        public PreventionModel(ILogger<PreventionModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

Pages/Privacy.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace covidwatch.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

Pages/Testing.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using covidwatch.Model;
using covidwatch.services;
using covidwatch.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
namespace covidwatch.Pages
{
    public class TestingModel : PageModel
    {
        private readonly ILogger<TestingModel> _logger;
        /// private JsonUserReaderService Jsonservice;
        public UsersService DBservice;
        public IEnumerable<User> Users; 
        public AssessmentCenterService ACservice;
        public IEnumerable<AssessmentCenter> AssessmentCenters;
        private object jsonservice;

        public TestingModel(ILogger<TestingModel> logger, JsonUserReaderService jurs, UsersService uServ, AssessmentCenterService aServ) 
        {
            _logger = logger;
            jsonservice = jurs;
            DBservice = uServ;
            ACservice = aServ;
        }
        public void OnGet()
        {
            Users = DBservice.Get();
            AssessmentCenters = ACservice.Get();
        }
        public void OnPost()
        {
         
        }
        
    }
}

Pages/Track.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace covidwatch.Pages
{
    public class TrackModel : PageModel
    {
        private readonly ILogger<TrackModel> _logger;

        public TrackModel(ILogger<TrackModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

Pages/About.cshtml
@page
@model AboutModel
@{
    ViewData["Title"] = "About Us";
}
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-03JP1WSP3N"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-03JP1WSP3N');
</script>
<h1>@ViewData["Title"]</h1>
<html>
<script type="text/javascript">
$(document).ready(function() {
  $('#mailbutton_mitch').click(function(event) {
    window.location = "mailto:mbate052@uottawa.ca";
  });
  $('#mailbutton_xiola').click(function(event) {
    window.location = "mailto:xbosw051@uottawa.ca";
  });
  $('#mailbutton_romane').click(function(event) {
    window.location = "mailto:rleri026@uottawa.ca";
  });
  $('#mailbutton_chloe').click(function(event) {
    window.location = "mailto:span063@uottawa.ca";
  });
  $('#mailbutton_henry').click(function(event) {
    window.location = "mailto:htadj034@uottawa.ca";
  });
  $('#mailbutton_ruijia').click(function(event) {
    window.location = "mailto:rma013@uottawa.ca";
  });
});
</script>
<body>
  <div class="container">
    <div class="row" style="margin-top: 10px; margin-bottom: 10px;">
        <div class="card border-secondary" style="background-color: var(--background-color); d-flex justify-content-center">
          <h5 style="color: var(--text-color)" class="card-header">Thanks for visiting COVID Watch!</h5>
          <div class="card-body">
            <h5 style="color: var(--text-color)" class="card-title">A little about us...</h5>
            <p class="card-text">Our website was founded on March 10, 2020 to help people respond better to COVID-19. We
              believe it is critical to keep everyone informed during this challenging time. We are committed to providing support to
              family, friends and the uOttawa community so that they can stay healthy. We wanted to create an accessible platform for
              students and the general public that has informative and educational news.</p>
            <p class="card-text">We inform people of the symptoms of COVID-19. We teach them how to protect
              themselves from being infected.</p>
            <h5 style="color: var(--text-color)" class="card-title">Our mission:</h5>
            <p class="card-text">To share the latest news about COVID-19, educate the public about healthy and safty protocols
              and reduce the spread of the virus.</p>
            <p class="card-text">We provide current news on the pandemic in Canada and around the globe. In addition,
              we closely monitor our data to ensure it's accurate and valid. We have developed newletters and regular
              updates for our users on the most recent travel regulations, Health Canada announcements
              and research regarding this matter.</p>
          </div>
        </div>
    </div>
  </div>
  <div class="container">
    <div class="row d-flex justify-content-center">
      <div class="col-sm-6 col-lg-3 py-2">
        <div style="background-color: var(--background-color)" class="card h-100 border-secondary">
          <div class="card-body d-flex flex-column">
            <h4 style="color: var(--text-color)" class="card-header" style="margin-bottom: 10px;">Mitchyl Bateman</h4>
            <p class="card-text">Specialized in Business Technology Management.</p>
            <a href="#" id="mailbutton_mitch" class="card-text mt-auto"><small class="text-muted">Contact Mitchyl</small></a>
          </div>
        </div>
      </div>
      <div class="col-sm-6 col-lg-3 py-2">
        <div style="background-color: var(--background-color)" class="card h-100 border-secondary">
          <div class="card-body d-flex flex-column">
            <h4 style="color: var(--text-color)" class="card-header" style="margin-bottom: 10px;">Romane Le Riguer</h4>
            <p class="card-text">Specialized in Business Technology Management.</p>
            <a href="#" id="mailbutton_romane" class="card-text mt-auto"><small class="text-muted">Contact Romane</small></a>
          </div>
        </div>
      </div>
      <div class="col-sm-6 col-lg-3 py-2">
        <div style="background-color: var(--background-color)" class="card h-100 border-secondary">
          <div class="card-body d-flex flex-column">
            <h4 style="color: var(--text-color)" class="card-header" style="margin-bottom: 10px;">Henry Dumond Tadja</h4>
            <p class="card-text">Specialized in Business Technology Management, minor in Finance.</p>
            <a href="#" id="mailbutton_henry" class="card-text mt-auto"><small class="text-muted">Contact Henry</small></a>
          </div>
        </div>
      </div>
    </div>
    <div class="row d-flex justify-content-center">
      <div class="col-sm-6 col-lg-3 py-2">
        <div style="background-color: var(--background-color)" class="card h-100 border-secondary">
          <div class="card-body d-flex flex-column">
            <h4 style="color: var(--text-color)" class="card-header" style="margin-bottom: 10px;">Ruijia Ma</h4>
            <p class="card-text">Specialized in Business Technology Management.</p>
            <a href="#" id="mailbutton_ruijia" class="card-text mt-auto"><small class="text-muted">Contact Ruijia</small></a>
          </div>
        </div>
      </div>
      <div class="col-sm-6 col-lg-3 py-2">
        <div style="background-color: var(--background-color)" class="card h-100 border-secondary">
          <div class="card-body d-flex flex-column">
            <h4 style="color: var(--text-color)" class="card-header" style="margin-bottom: 10px;">Chloe Pan</h4>
            <p class="card-text">Specialized in International Development.</p>
            <a href="#" id="mailbutton_chloe" class="card-text mt-auto"><small class="text-muted">Contact Chloe</small></a>
          </div>
        </div>
      </div>
      <div class="col-sm-6 col-lg-3 py-2">
        <div style="background-color: var(--background-color)" class="card h-100 border-secondary">
          <div class="card-body d-flex flex-column">
            <h4 style="color: var(--text-color)" class="card-header" style="margin-bottom: 10px;">Xiola Boswarva</h4>
            <p class="card-text">Specialized in Business Technology Management.</p>
            <a href="#" id="mailbutton_xiola" class="card-text mt-auto"><small class="text-muted">Contact Xiola</small></a>
          </div>
        </div>
      </div>
      </div>
    </div>
  </div>
</body>

</html>

Pages/Create.cshtml
@page
@addTagHelper*, Microsoft.AspNetCore.Mvc.TagHelpers
@model CreateModel
@{
    ViewData["Title"] = "Create";
}
<html>

 <body>
    <div class="container">
        <div class="card border-secondary">
            <div class="card">
            <div class="card-header"><b>This page allows you to view all the users in the database. Visit the Login page to create users.</b> </div>
            <div class="row">
            @foreach (var pers in Model.Users)
                {
                    <div class="col-sm">
                        <div class="card">
                            <div class="card-body">
                                <p class="card-text">Username: @pers.Username</p>
                                <p class="card-text">Password: @pers.Password</p>
                            </div>
                        </div>
                    </div>
                }
            </div>
    </div>
</body>

</html>

Pages/Index.cshtml
@page
@model IndexModel
@{
  ViewData["Title"] = "Home page";
}
<html>
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-03JP1WSP3N"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-03JP1WSP3N');
</script>

<body>
  <style>
    .card-title{
      text-align: center;
    }
  </style>
  <div class="container">
    <div class="row">
      <div class="col d-flex justify-content-center">
        <div class="card border-secondary"
          style="width: 21rem; margin-bottom: 7px; background-color: var(--background-color);">
          <img class="card-img-top" src="~/Images/backgroundcanada.jpg" alt="Card image cap" width="600px" height="300px">
          <div class="card-body d-flex flex-column">
            <h5 style="color: var(--text-color)" class="card-title">Track</h5>
            <p class="card-text">Access our online tools for tracking the spread in Canadian provinces.</p>
            <a asp-page="/Track" class="btn btn-primary mt-auto">Go to Tracking</a>
          </div>
        </div>
      </div>
      <div class="col d-flex justify-content-center">
        <div class="card border-secondary"
          style="width: 21rem; margin-bottom: 7px; background-color: var(--background-color);">
          <img class="card-img-top" src="~/Images/wash.jpg" alt="Card image cap" width="600px" height="300px">
          <div class="card-body d-flex flex-column">
            <h5 style="color: var(--text-color)" class="card-title">Prevention</h5>
            <p class="card-text">Learn how you can help stop the spread of the deadly COVID-19 virus.</p>
            <a asp-page="/Prevention" class="btn btn-primary mt-auto">Go to Prevention</a>
          </div>
        </div>
      </div>
      <div class="col d-flex justify-content-center">
        <div class="card border-secondary"
          style="width: 21rem; margin-bottom: 7px; background-color: var(--background-color);">
          <img class="card-img-top" src="~/Images/backgroundselfassesment.gif" alt="Card image cap" width="600px" height="300px">
          <div class="card-body d-flex flex-column">
            <h5 style="color: var(--text-color)" class="card-title">Self-Assessment</h5>
            <p class="card-text">Take the Government of Ontario's self-assessment.</p>
            <a href="https://covid-19.ontario.ca/self-assessment/severe-symptoms" class="btn btn-primary mt-auto">Take
              Self-Assessment</a>
          </div>
        </div>
      </div>
      <div class="col d-flex justify-content-center">
        <div class="card border-secondary"
          style="width: 21rem; margin-bottom: 7px; background-color: var(--background-color);">
          <img class="card-img-top" src="~/Images/backgroundwho.jpg" alt="Card image cap" width="600px" height="300px">
          <div class="card-body d-flex flex-column">
            <h5 style="color: var(--text-color)" class="card-title">Health Guidelines</h5>
            <p class="card-text">The latest WHO guidelines on COVID-19.</p>
            <a href="https://www.who.int/news-room/feature-stories/detail/a-guide-to-who-s-guidance"
              class="btn btn-primary mt-auto">Go to WHO</a>
          </div>
        </div>
      </div>
      <div class="col d-flex justify-content-center">
        <div class="card border-secondary"
          style="width: 21rem; margin-bottom: 7px; background-color: var(--background-color);">
          <img class="card-img-top" src="~/Images/test.jpg" alt="Card image cap" width="600px" height="300px">
          <div class="card-body d-flex flex-column">
            <h5 style="color: var(--text-color)" class="card-title">COVID-19 testing</h5>
            <p class="card-text">Find local COVID-19 testing centres and hours.</p>
            <a asp-page="/Testing" class="btn btn-primary mt-auto">Locate testing centres</a>
          </div>
        </div>
      </div>
      <div class="col d-flex justify-content-center">
        <div class="card border-secondary"
          style="width: 21rem; margin-bottom: 7px; background-color: var(--background-color);">
          <img class="card-img-top" src="~/Images/Teampic.jpg" alt="Card image cap" width="600px" height="300px">
          <div class="card-body d-flex flex-column">
            <h5 style="color: var(--text-color)" class="card-title">About Us</h5>
            <p class="card-text">Learn about our team and our initiative.</p>
            <a asp-page="/About" class="btn btn-primary mt-auto">Learn about us</a>
          </div>
        </div>
      </div>
    </div>
  </div>
</body>


</html>

Pages/Login.cshtml
@page
@model LoginModel
<h1>@ViewData["Title"]</h1>
<script>
    function setFormMessage(formElement, type, message) {
        const messageElement = formElement.querySelector(".form__message");

        messageElement.textContent = message;
        messageElement.classList.remove("form__message--success", "form__message--error");
        messageElement.classList.add(`form__message--${type}`);
    }

    function setInputError(inputElement, message) {
        inputElement.classList.add("form__input--error");
        inputElement.parentElement.querySelector(".form__input-error-message").textContent = message;
    }

    function clearInputError(inputElement) {
        inputElement.classList.remove("form__input--error");
        inputElement.parentElement.querySelector(".form__input-error-message").textContent = "";
    }

    document.addEventListener("DOMContentLoaded", () => {
        const loginForm = document.querySelector("#login");
        const createAccountForm = document.querySelector("#createAccount");

        document.querySelector("#linkCreateAccount").addEventListener("click", e => {
            e.preventDefault();
            loginForm.classList.add("form--hidden");
            createAccountForm.classList.remove("form--hidden");
        });

        document.querySelector("#linkLogin").addEventListener("click", e => {
            e.preventDefault();
            loginForm.classList.remove("form--hidden");
            createAccountForm.classList.add("form--hidden");
        });

        loginForm.addEventListener("submit", e => {
            e.preventDefault();

            // Perform your AJAX/Fetch login

            setFormMessage(loginForm, "error", "Invalid username/password combination");
        });

        document.querySelectorAll(".form__input").forEach(inputElement => {
            inputElement.addEventListener("blur", e => {
                if (e.target.id === "signupUsername" && e.target.value.length > 0 && e.target.value.length < 10) {
                    setInputError(inputElement, "Username must be at least 10 characters in length");
                }
            });

            inputElement.addEventListener("input", e => {
                clearInputError(inputElement);
            });
        });
    });
</script>
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-03JP1WSP3N"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-03JP1WSP3N');
</script>
<html>

<body class="log" style="background-color: var(--background-color)">
    <div class="container">
        <form class="form" id="login" method="get">
            <h1 style="color: black" class="form__title">Login</h1>
            <div class="form__message form__message--error"></div>
            <div class="form__input-group">
                <input type="text" id="txtUserName" name="Username" class="form__input" autofocus placeholder="Username or email">
                <div class="form__input-error-message"></div>
            </div>
            <div class="form__input-group">
                <input type="password" id="txtPassword" name="Password" class="form__input" autofocus placeholder="Password">
                <div class="form__input-error-message"></div>
            </div>
            <button class="form__button" type="submit">Continue</button>
            <p class="form__text">
                <a href="#" class="form__link">Forgot your password?</a>
            </p>
            <p class="form__text">
                <a class="form__link" href="./" id="linkCreateAccount">Don't have an account? Create account</a>
            </p>
        </form>
        <form method="post" class="form form--hidden" id="createAccount">
            <h1 class="form__title">Create Account</h1>
            <div class="form__message form__message--error"></div>
            <div class="form__input-group">
                <input type="text" id="txtUsername" name="Username" class="form__input" autofocus placeholder="Username">
                <div class="form__input-error-message"></div>
            </div>
            <div class="form__input-group">
                <input type="password" id="txtPassword" name="Password" class="form__input" autofocus placeholder="Password">
                <div class="form__input-error-message"></div>
            </div>
            <div class="form__input-group">
                <input type="password" class="form__input" autofocus placeholder="Confirm password">
                <div class="form__input-error-message"></div>
            </div>
            <button class="form__button" type="submit" value="Submit" asp-page-handler="Submit">Create Account</button>
            <p class="form__text">
                <a class="form__link" href="./" id="linkLogin">Already have an account? Sign in</a>
            </p>
        </form>
    </div>
    <script src="main.js"></script>
</body>

</html>

Pages/Prevention.cshtml
@page
@model PreventionModel
@{
   ViewData["Title"] = "Prevention";
}
<h1>@ViewData["Title"]</h1>
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-03JP1WSP3N"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-03JP1WSP3N');
</script>

<body class="body">
   <div>
      <h2 style="color: var(--text-color)">How to Protect Yourself and Your Family</h2></br>
      <h3 style="color: var(--text-color)">Cleaning</h3>
      <ul style="color: var(--text-color)">
         <li>Clean and disinfect frequently touched items daily.</li>
         <li>Disinfect anything you brought from outside your home using 90% alcohol.</li>
         <li>Regular cleaning can also help you stay organized and positive throughout this time.</li>
         <li>Keep in mind that the virus can live up to two weeks. Sanitize your parcels and packages if needed.</li>
      </ul>
      <h3 style="color: var(--text-color)">Protecting Your Community</h3>
      <ul style="color: var(--text-color)">
         <li>It's important to understand that this virus brings potential risks to people around you, especially to
            elderly people and people with underlying conditions.</li>
         <li>Respect others. Practice social distancing religiously and avoid close contact if you live with high risk
            individuals.</li>
         <li><span style="font-weight: bold; color:red">ALWAYS</span> keep your mask on for your own safety and for the
            safety of others. <a href='https://www.youtube.com/watch?v=adB8RW4I3o4' style="color: black;"
               target="_blank">Click here if you are not familiar with how to properly wear a mask.</a></li>
         <li>Be honest. You should inform anyone with whom you had close contact if you test positive.</li>
         <li>Help each other. While close contact is discouraged, you can always help out people who are in need. Simple
            gestures such as dropping off groceries or calling people will help relieve their stress.</li>
      </ul>

   </div>

</body>

Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - COVID Watch</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="~/css/new.css" />
    <!-- Global site tag (gtag.js) - Google Analytics - with the group5covid19 Measurement ID.  -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=G-03JP1WSP3N"></script>
    <script>
        window.dataLayer = window.dataLayer || [];
        function gtag() { dataLayer.push(arguments); }
        gtag('js', new Date());

        gtag('config', 'G-03JP1WSP3N');
    </script>
    <script type="text/javascript"
        src="//translate.google.com/translate_a/element.js?cb=googleTranslateElementInit"></script>
    <script type="text/javascript">
        window.onload = function () {
            const btn = document.querySelector(".btn-toggle");
            const prefersDarkScheme = window.matchMedia("(prefers-color-scheme: dark)");
            const currentTheme = localStorage.getItem("theme");
            if (currentTheme == "dark") {
                document.body.classList.toggle("dark-theme");
            } else if (currentTheme == "light") {
                document.body.classList.toggle("light-theme");
            }
            btn.addEventListener("click", function () {
                if (prefersDarkScheme.matches) {
                    document.body.classList.toggle("light-theme");
                    var theme = document.body.classList.contains("light-theme")
                        ? "light"
                        : "dark";
                } else {
                    document.body.classList.toggle("dark-theme");
                    var theme = document.body.classList.contains("dark-theme")
                        ? "dark"
                        : "light";
                }
                localStorage.setItem("theme", theme);
            });
        }
    </script>
    <script type="text/javascript">
        function googleTranslateElementInit() {
            new google.translate.TranslateElement({ pageLanguage: 'en', layout: google.translate.TranslateElement.InlineLayout.SIMPLE }, 'google_translate_element');
        }
    </script>
</head>

<body>
    <header>
        <nav class="header nav navbar navbar-expand-sm navbar-toggleable-sm navbar-light border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand text-light" asp-area="" asp-page="/Index">Covid Watch</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse"
                    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-light" style="color:white;" disppasp-area=""
                                asp-page="/Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-page="/About">About</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-page="/Track">Tracking</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-page="/Testing">Testing Centres</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-page="/Create">View Users</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-page="/Login">Login</a>
                        </li>
                    </ul>
                </div>
                <div class="mx-auto order-5">
                    <button type="button" class="btn btn-primary btn-toggle"
                        style="margin-right: 10px; margin-left: 10px;">Dark Mode</button>
                </div>
                <div id="google_translate_element" class="mx-auto order-0"></div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - Covid Watch - <a asp-area="" asp-page="/About">About</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>

</html>